import { Operation, PipelineDeal, Counterparty, ChecklistItem } from "./types";

// Country flag emoji helper
export const countryFlags: Record<string, string> = {
  UAE: "🇦🇪",
  DRC: "🇨🇩",
  Switzerland: "🇨🇭",
  Dubai: "🇦🇪",
  Spain: "🇪🇸",
  Brazil: "🇧🇷",
  Morocco: "🇲🇦",
  China: "🇨🇳",
  Turkey: "🇹🇷",
  Ghana: "🇬🇭",
  Germany: "🇩🇪",
  USA: "🇺🇸",
  UK: "🇬🇧",
  Singapore: "🇸🇬",
  Nigeria: "🇳🇬",
};

// --- Mock Operations (Recent Deals) ---
export const mockOperations: Operation[] = [
  {
    id: "OP-001",
    product: "Copper Cathodes",
    buyer: "Gulf Metals FZE",
    seller: "Katanga Mining DRC",
    country: "UAE / DRC",
    status: "Under Review",
    riskScore: 52,
    riskLevel: "medium",
    value: "$4,200,000",
    currency: "USD",
    date: "2024-12-10",
    origin: "DRC",
    destination: "UAE",
    incoterm: "CIF Dubai",
    paymentTerms: "LC at sight",
  },
  {
    id: "OP-002",
    product: "BTC OTC Block",
    buyer: "Alpine Digital SA",
    seller: "MENA Crypto LLC",
    country: "Switzerland / Dubai",
    status: "High Risk",
    riskScore: 28,
    riskLevel: "high",
    value: "$8,500,000",
    currency: "USD",
    date: "2024-12-08",
    origin: "Dubai",
    destination: "Switzerland",
    incoterm: "N/A",
    paymentTerms: "Wire Transfer",
  },
  {
    id: "OP-003",
    product: "Sugar ICUMSA 45",
    buyer: "Iberian Foods SL",
    seller: "Canavieiras Export Ltda",
    country: "Spain / Brazil",
    status: "Qualified",
    riskScore: 74,
    riskLevel: "qualified",
    value: "$1,850,000",
    currency: "USD",
    date: "2024-12-05",
    origin: "Brazil",
    destination: "Spain",
    incoterm: "FOB Santos",
    paymentTerms: "SBLC",
  },
  {
    id: "OP-004",
    product: "Stainless Steel Coils",
    buyer: "Atlas Steel Morocco",
    seller: "Baosteel Group",
    country: "Morocco / China",
    status: "Negotiation",
    riskScore: 88,
    riskLevel: "strong",
    value: "$3,100,000",
    currency: "USD",
    date: "2024-12-03",
    origin: "China",
    destination: "Morocco",
    incoterm: "CFR Casablanca",
    paymentTerms: "LC 60 days",
  },
  {
    id: "OP-005",
    product: "Gold Doré Bars",
    buyer: "Ankara Precious Metals",
    seller: "GoldFields Ghana",
    country: "Turkey / Ghana",
    status: "High Risk",
    riskScore: 22,
    riskLevel: "high",
    value: "$12,750,000",
    currency: "USD",
    date: "2024-12-01",
    origin: "Ghana",
    destination: "Turkey",
    incoterm: "EXW Accra",
    paymentTerms: "MT103",
  },
  {
    id: "OP-006",
    product: "Crude Palm Oil",
    buyer: "Rotterdam Oils BV",
    seller: "PT Sinar Mas",
    country: "Netherlands / Indonesia",
    status: "Closed Won",
    riskScore: 81,
    riskLevel: "strong",
    value: "$2,400,000",
    currency: "USD",
    date: "2024-11-28",
    origin: "Indonesia",
    destination: "Netherlands",
    incoterm: "CIF Rotterdam",
    paymentTerms: "LC at sight",
  },
];

// --- Mock Pipeline Deals ---
export const mockPipelineDeals: PipelineDeal[] = [
  {
    id: "PL-001",
    product: "Copper Cathodes",
    company: "Gulf Metals FZE",
    value: "$4.2M",
    score: 52,
    riskLevel: "medium",
    country: "UAE",
    status: "Under Review",
    flag: "🇦🇪",
  },
  {
    id: "PL-002",
    product: "BTC OTC Block",
    company: "Alpine Digital SA",
    value: "$8.5M",
    score: 28,
    riskLevel: "high",
    country: "Switzerland",
    status: "High Risk",
    flag: "🇨🇭",
  },
  {
    id: "PL-003",
    product: "Sugar ICUMSA 45",
    company: "Iberian Foods SL",
    value: "$1.85M",
    score: 74,
    riskLevel: "qualified",
    country: "Spain",
    status: "Qualified",
    flag: "🇪🇸",
  },
  {
    id: "PL-004",
    product: "Stainless Steel Coils",
    company: "Atlas Steel Morocco",
    value: "$3.1M",
    score: 88,
    riskLevel: "strong",
    country: "Morocco",
    status: "Negotiation",
    flag: "🇲🇦",
  },
  {
    id: "PL-005",
    product: "Gold Doré Bars",
    company: "Ankara Precious Metals",
    value: "$12.75M",
    score: 22,
    riskLevel: "high",
    country: "Turkey",
    status: "High Risk",
    flag: "🇹🇷",
  },
  {
    id: "PL-006",
    product: "Crude Palm Oil",
    company: "Rotterdam Oils BV",
    value: "$2.4M",
    score: 81,
    riskLevel: "strong",
    country: "Netherlands",
    status: "Closed Won",
    flag: "🇳🇱",
  },
  {
    id: "PL-007",
    product: "Lithium Carbonate",
    company: "EV Battery Corp",
    value: "$6.3M",
    score: 45,
    riskLevel: "medium",
    country: "Germany",
    status: "New Lead",
    flag: "🇩🇪",
  },
  {
    id: "PL-008",
    product: "Cashew Nuts",
    company: "Lagos Agri Exports",
    value: "$0.9M",
    score: 15,
    riskLevel: "critical",
    country: "Nigeria",
    status: "Rejected",
    flag: "🇳🇬",
  },
  {
    id: "PL-009",
    product: "LNG Spot",
    company: "Singapore Energy Ltd",
    value: "$18M",
    score: 67,
    riskLevel: "qualified",
    country: "Singapore",
    status: "Negotiation",
    flag: "🇸🇬",
  },
];

// --- Mock Counterparties ---
export const mockCounterparties: Counterparty[] = [
  {
    id: "CP-001",
    name: "Khalid Al-Rashid",
    company: "Gulf Metals FZE",
    country: "UAE",
    type: "Buyer",
    trustScore: 62,
    riskLevel: "medium",
    previousDeals: 3,
    notes: "Requested unrealistic discount on last deal. Verify POF before proceeding.",
    email: "khalid@gulfmetals.ae",
    flag: "🇦🇪",
  },
  {
    id: "CP-002",
    name: "Jean-Pierre Müller",
    company: "Alpine Digital SA",
    country: "Switzerland",
    type: "Buyer",
    trustScore: 31,
    riskLevel: "high",
    previousDeals: 1,
    notes: "OTC crypto deal. No verifiable POF. Uses generic email. High urgency.",
    email: "jp.muller@gmail.com",
    flag: "🇨🇭",
  },
  {
    id: "CP-003",
    name: "Carlos Medina",
    company: "Iberian Foods SL",
    country: "Spain",
    type: "Buyer",
    trustScore: 78,
    riskLevel: "qualified",
    previousDeals: 5,
    notes: "Established food importer. SBLC confirmed. Corporate email and website verified.",
    email: "c.medina@iberianfoods.es",
    flag: "🇪🇸",
  },
  {
    id: "CP-004",
    name: "Mohammed Fassi",
    company: "Atlas Steel Morocco",
    country: "Morocco",
    type: "Buyer",
    trustScore: 91,
    riskLevel: "strong",
    previousDeals: 8,
    notes: "Top-tier buyer. Full KYC passed. LC from Attijariwafa Bank. No issues.",
    email: "m.fassi@atlassteel.ma",
    flag: "🇲🇦",
  },
  {
    id: "CP-005",
    name: "Emre Demir",
    company: "Ankara Precious Metals",
    country: "Turkey",
    type: "Buyer",
    trustScore: 24,
    riskLevel: "high",
    previousDeals: 2,
    notes: "Rushed timelines. Refuses proper KYC. MT103 payment term is a red flag.",
    email: "edemir@ankarapm.com",
    flag: "🇹🇷",
  },
  {
    id: "CP-006",
    name: "Zhang Wei",
    company: "Baosteel Group",
    country: "China",
    type: "Seller",
    trustScore: 87,
    riskLevel: "strong",
    previousDeals: 12,
    notes: "State-owned enterprise. Full export documentation. ISO certified. Reliable.",
    email: "zhang.wei@baosteel.com",
    flag: "🇨🇳",
  },
  {
    id: "CP-007",
    name: "Amara Diallo",
    company: "Katanga Mining DRC",
    country: "DRC",
    type: "Seller",
    trustScore: 55,
    riskLevel: "medium",
    previousDeals: 4,
    notes: "Export license verified. Some document inconsistencies in last shipment.",
    email: "a.diallo@katangamining.cd",
    flag: "🇨🇩",
  },
  {
    id: "CP-008",
    name: "Roberto Santana",
    company: "Canavieiras Export Ltda",
    country: "Brazil",
    type: "Seller",
    trustScore: 82,
    riskLevel: "strong",
    previousDeals: 7,
    notes: "Established sugar exporter. All certifications current. FOB Santos regular.",
    email: "r.santana@canavieiras.com.br",
    flag: "🇧🇷",
  },
  {
    id: "CP-009",
    name: "Victor Asante",
    company: "GoldFields Ghana",
    country: "Ghana",
    type: "Seller",
    trustScore: 29,
    riskLevel: "high",
    previousDeals: 2,
    notes: "Export documentation incomplete. Origin certificate disputed. EXW terms risk.",
    email: "v.asante@goldfieldsgh.com",
    flag: "🇬🇭",
  },
  {
    id: "CP-010",
    name: "Sophie Laurent",
    company: "EuroBroker SA",
    country: "Switzerland",
    type: "Broker",
    trustScore: 73,
    riskLevel: "qualified",
    previousDeals: 15,
    notes: "Experienced commodities broker. Clear mandate. Commission structure agreed.",
    email: "s.laurent@eurobroker.ch",
    flag: "🇨🇭",
  },
  {
    id: "CP-011",
    name: "David Okafor",
    company: "West Africa Trade Links",
    country: "Nigeria",
    type: "Mandate",
    trustScore: 18,
    riskLevel: "critical",
    previousDeals: 0,
    notes: "No verifiable mandate. No company website. Claims direct seller access. Avoid.",
    email: "david.okafor123@yahoo.com",
    flag: "🇳🇬",
  },
  {
    id: "CP-012",
    name: "Anna Bergstrom",
    company: "Nordic Trade Partners AB",
    country: "UK",
    type: "Broker",
    trustScore: 85,
    riskLevel: "strong",
    previousDeals: 9,
    notes: "Excellent track record. Regulated entity. Clear NCNDA signed. Recommended.",
    email: "a.bergstrom@nordictp.com",
    flag: "🇬🇧",
  },
];

// --- Default Due Diligence Checklist ---
export const defaultChecklist: ChecklistItem[] = [
  // Buyer
  { id: "b1", label: "Corporate email verified", category: "buyer", checked: false, critical: true },
  { id: "b2", label: "Company website confirmed", category: "buyer", checked: false, critical: false },
  { id: "b3", label: "Proof of Funds (POF) received", category: "buyer", checked: false, critical: true },
  { id: "b4", label: "KYC documentation accepted", category: "buyer", checked: false, critical: true },
  { id: "b5", label: "Direct buyer confirmed (no layers)", category: "buyer", checked: false, critical: true },
  // Seller
  { id: "s1", label: "Proof of Product (POP) available", category: "seller", checked: false, critical: true },
  { id: "s2", label: "Product origin verified", category: "seller", checked: false, critical: true },
  { id: "s3", label: "Company registration confirmed", category: "seller", checked: false, critical: false },
  { id: "s4", label: "Export capacity demonstrated", category: "seller", checked: false, critical: false },
  { id: "s5", label: "Procedure consistency checked", category: "seller", checked: false, critical: true },
  // Broker
  { id: "br1", label: "Mandate document available", category: "broker", checked: false, critical: true },
  { id: "br2", label: "Position in chain is clear", category: "broker", checked: false, critical: true },
  { id: "br3", label: "Number of intermediaries verified (max 2)", category: "broker", checked: false, critical: false },
  { id: "br4", label: "Commission structure defined", category: "broker", checked: false, critical: false },
  { id: "br5", label: "Bypass risk assessed (NCNDA signed)", category: "broker", checked: false, critical: true },
];

// --- Dashboard Stats ---
export const dashboardStats = {
  activeDeals: 9,
  highRiskDeals: 3,
  qualifiedCounterparties: 6,
  estimatedVolume: "$58.7M",
  averageRiskScore: 57,
};

// --- Risk Distribution Chart Data ---
export const riskDistributionData = [
  { name: "Strong", value: 2, color: "#10b981" },
  { name: "Qualified", value: 2, color: "#1A6FA5" },
  { name: "Medium", value: 2, color: "#f59e0b" },
  { name: "High Risk", value: 2, color: "#f97316" },
  { name: "Critical", value: 1, color: "#ef4444" },
];

// --- Pipeline Value Chart Data ---
export const pipelineValueData = [
  { stage: "New Lead", value: 6.3, deals: 1 },
  { stage: "Under Review", value: 4.2, deals: 1 },
  { stage: "Qualified", value: 1.85, deals: 1 },
  { stage: "Negotiation", value: 21.1, deals: 2 },
  { stage: "High Risk", value: 21.25, deals: 2 },
  { stage: "Closed Won", value: 2.4, deals: 1 },
];

// --- Monthly Deal Trend ---
export const dealTrendData = [
  { month: "Jul", deals: 4, value: 12.1 },
  { month: "Aug", deals: 6, value: 18.4 },
  { month: "Sep", deals: 5, value: 15.7 },
  { month: "Oct", deals: 8, value: 31.2 },
  { month: "Nov", deals: 7, value: 27.8 },
  { month: "Dec", deals: 9, value: 38.5 },
];
